/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;
import java.util.ArrayList;

public class App {

    //Search two strings in an arraylist 
    //return true if both of them appear in the arraylist 
    //else return false
    public static boolean searchString(ArrayList<String> array, String firstString, String secondString) {

        boolean isFirstPresent = false;
        boolean isSecondPresent = false;

        if (array == null) return false;

        for (String arrayElement : array){
            if (arrayElement.contains(firstString)){
                isFirstPresent = true;
            }
            if (arrayElement.contains(secondString)){
                isSecondPresent = true;
              }
        }

        if(isFirstPresent == true && isSecondPresent == true){
            return true;
        }else{
            return false;
        }
    }

    public static void main(String[] args) {
    }
}
